export const ADD_DATA = "ADD_DATA";
export const ADD_ADMIN_REQUEST = 'ADD_ADMIN_REQUEST';
export const ADD_ADMIN_REJECT = 'ADD_ADMIN_REJECT';

// get 
export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const FAILURE_DATA = 'FAILURE_DATA';

export const DELETE_ADMIN_REQUEST = 'DELETE_ADMIN_REQUEST';
export const DELETE_ADMIN_REJECT = 'DELETE_ADMIN_REJECT';
export const DELETE_ADMIN = 'DELETE_ADMIN';

export const SINGLE_ADMIN_REQUEST = "SINGLE_ADMIN_REQUEST";
export const SINGLE_ADMIN_RECEIVE = "SINGLE_ADMIN_RECEIVE";
export const SINGLE_ADMIN_REJECT = "SINGLE_ADMIN_FAILURE";

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const USERLOGINREQ = 'USERLOGINREQ';
export const USERLOGINRES = 'USERLOGINRES';
export const USERLOGINREJ = 'USERLOGINREJ';

export const LOGOUTREQ = 'USERLOGINREQ';
export const LOGOUTRES = 'USERLOGINRES';
export const LOGOUTREJ = 'USERLOGINREJ';

export const GOOGLELOGINREQ = 'USERLOGINREQ';
export const GOOGLELOGINRES = 'USERLOGINRES';
export const GOOGLELOGINREJ = 'USERLOGINREJ';